export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const SEND_CONTACT_FORM_SUCCESS = "SEND_CONTACT_FORM_SUCCESS";

// export const INITIAL_LOAD_SUCCESS = "INITIAL_LOAD_SUCCESS";
// export const INITIAL_LOAD_FAILURE = "INITIAL_LOAD_FAILURE";

// portfolios types
export const LOAD_PORTFOLIOS_SUCCESS = "LOAD_PORTFOLIOS_SUCCESS";
export const LOAD_PORTFOLIOS_FAILURE = "LOAD_PORTFOLIOS_FAILURE";
export const CREATE_PORTFOLIO_SUCCESS = "CREATE_PORTFOLIO_SUCCESS";
export const UPDATE_PORTFOLIO_SUCCESS = "UPDATE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_SUCCESS = "DELETE_PORTFOLIO_SUCCESS";
export const DELETE_PORTFOLIO_OPTIMISTIC = "DELETE_PORTFOLIO_OPTIMISTIC";
export const REMOVE_PORTFOLIOS_SUCCESS = "REMOVE_PORTFOLIOS_SUCCESS";
export const LOAD_PORTFOLIOS_LIST_SUCCESS = "LOAD_PORTFOLIOS_LIST_SUCCESS";

// holdings types
export const LOAD_PORTFOLIO_HOLDINGS_SUCCESS =
  "LOAD_PORTFOLIO_HOLDINGS_SUCCESS";
export const LOAD_PORTFOLIO_HOLDINGS_FAILURE =
  "LOAD_PORTFOLIO_HOLDINGS_FAILURE";
export const REMOVE_HOLDINGS_SUCCESS = "REMOVE_HOLDINGS_SUCCESS";
export const ADD_PUBLIC_HOLDING_SUCCESS = "ADD_PUBLIC_HOLDING_SUCCESS";
export const REMOVE_PUBLIC_HOLDINGS_SUCCESS = "REMOVE_PUBLIC_HOLDINGS_SUCCESS";
export const REMOVE_ALL_PUBLIC_HOLDINGS_SUCCESS =
  "REMOVE_ALL_PUBLIC_HOLDINGS_SUCCESS";
export const ADD_PUBLIC_PORTFOLIO_SUCCESS = "ADD_PUBLIC_PORTFOLIO_SUCCESS";
export const DELETE_HOLDINGS_SUCCESS = "DELETE_HOLDINGS_SUCCESS";
export const DELETE_PORT_HOLDING_TRANS_SUCCESS =
  "DELETE_PORT_HOLDING_TRANS_SUCCESS";

// brokers types
export const LOAD_BROKERS_SUCCESS = "LOAD_BROKERS_SUCCESS";
export const LOAD_BROKERS_FAILURE = "LOAD_BROKERS_FAILURE";
export const REMOVE_BROKERS_SUCCESS = "REMOVE_BROKERS_SUCCESS";
export const ADD_BROKER_SUCCESS = "ADD_BROKER_SUCCESS";
export const UPDATE_BROKER_SUCCESS = "UPDATE_BROKER_SUCCESS";
export const DELETE_BROKER_SUCCESS = "DELETE_BROKER_SUCCESS";
export const DELETE_BROKER_OPTIMISTIC = "DELETE_BROKER_OPTIMISTIC";
export const ADD_PUBLIC_BROKER_SUCCESS = "ADD_PUBLIC_BROKER_SUCCESS";

// sign up types
export const SEND_SIGNUP_FORM_SUCCESS = "SEND_SIGNUP_FORM_SUCCESS";
export const SEND_SIGNUP_FORM_FAILURE = "SEND_SIGNUP_FORM_FAILURE";
export const CLEAR_SIGNUP_ATTEMPT_SUCCESS = "CLEAR_SIGNUP_ATTEMPT_SUCCESS";

// sign in types
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const CLEAR_SIGNIN_ATTEMPT_SUCCESS = "CLEAR_SIGNIN_ATTEMPT_SUCCESS";

// transactions
export const LOAD_BUY_TRANSACTIONS_SUCCESS = "LOAD_BUY_TRANSACTIONS_SUCCESS";
export const LOAD_BUY_TRANSACTIONS_FAILURE = "LOAD_BUY_TRANSACTIONS_FAILURE";
export const REMOVE_BUY_TRANSACTIONS_SUCCESS =
  "REMOVE_BUY_TRANSACTIONS_SUCCESS";

export const UPDATE_BUY_TRANSACTION_SUCCESS = "UPDATE_BUY_TRANSACTION_SUCCESS";
export const UPDATE_BUY_TRANSACTION_FAILURE = "UPDATE_BUY_TRANSACTION_FAILURE";
export const ADD_BUY_TRANSACTION_SUCCESS = "ADD_BUY_TRANSACTION_SUCCESS";

export const DELETE_BUY_TRANSACTIONS_SUCCESS =
  "DELETE_BUY_TRANSACTIONS_SUCCESS";
export const DELETE_BUY_TRANSACTIONS_FAILURE =
  "DELETE_BUY_TRANSACTIONS_FAILURE";

export const DELETE_HOLDING_TRANSACTIONS_SUCCESS =
  "DELETE_HOLDING_TRANSACTIONS_SUCCESS";
export const DELETE_HOLDING_TRANSACTIONS_FAILURE =
  "DELETE_HOLDING_TRANSACTIONS_FAILURE";
